theme: jekyll-theme-cayman
title: metareflection.seas.harvard.edu
description: 
github:
  repository.name: metareflection.seas.harvard.edu
  repository_url: https://github.com/metareflection
  owner.name: metareflection.seas.harvard.edu
  owner_url: https://metareflection.seas.harvard.edu
  is_project_page: true
